service: moskit-cf-options-lambda-api
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 60
  httpApi:
    cors: true

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'